repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [commit, push]
        language: system
        entry: pipenv run pytest
        types: [python]

      - id: pytest-cov
        name: pytest
        stages: [commit, push]
        language: system
        entry: pipenv run pytest --cov --cov-fail-under=100
        types: [python]
        pass_filenames: false